### ISSUE TITLE
large backpack crashes

### ISSUE THREAD

**Issue by iTzAndrew33212** [VennDev/VBackpack#2]
hi there, as I placed the chest down to receive the backpack, server crashes with this error code

Jul 04 09:09 [Server] INFO #26 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[36] /, string[44] /plugins/)
Jul 04 09:09 [Server] INFO #25 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
Jul 04 09:09 [Server] INFO #24 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688458154.0683)
Jul 04 09:09 [Server] INFO #23 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
Jul 04 09:09 [Server] INFO #22 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
Jul 04 09:09 [Server] INFO #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
Jul 04 09:09 [Server] INFO #20 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#187301)
Jul 04 09:09 [Server] INFO #19 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[286] ..BB*...).i................W@.a......3.....v..q.....R..w......Z.......T....;=.)
Jul 04 09:09 [Server] INFO #18 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[277] c.ab.Sa..`.|.........(..Y......%.H04la....?#....;CJfqANb%..._bn. ....>.E...N....)
Jul 04 09:09 [Server] INFO #17 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#70844, string[418] .......l..................display...Name....5Large Backpack....id_backpack .2535)
Jul 04 09:09 [Server] INFO #16 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#143167)
Jul 04 09:09 [Server] INFO #15 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(94): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#70844)
Jul 04 09:09 [Server] INFO #14 pmsrc/src/network/mcpe/handler/InGamePacketHandler(340): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemTransactionData#70843)
Jul 04 09:09 [Server] INFO #13 pmsrc/src/network/mcpe/handler/InGamePacketHandler(487): pocketmine\player\Player->interactBlock(object pocketmine\math\Vector3#70974, int 1, object pocketmine\math\Vector3#70834)
Jul 04 09:09 [Server] INFO #12 pmsrc/src/player/Player(1807): pocketmine\world\World->useItemOn(object pocketmine\math\Vector3#70974, object pocketmine\item\ItemBlock#70961, int 1, object pocketmine\math\Vector3#70911, object pocketmine\player\Player#143677, true, array[0])
Jul 04 09:09 [Server] INFO #11 pmsrc/src/world/World(2063): pocketmine\event\Event->call()
Jul 04 09:09 [Server] INFO #10 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerInteractEvent#70954)
Jul 04 09:09 [Server] INFO #9 pmsrc/src/event/RegisteredListener(61): vennv\vbackpack\listener\EventListener->onPlayerInteract(object pocketmine\event\player\PlayerInteractEvent#70954)
Jul 04 09:09 [Server] INFO #8 plugins/VBackpack.phar/src/vennv/vbackpack/listener/EventListener(41): vennv\vbackpack\data\DataManager::openBackpack(object pocketmine\player\Player#143677, object pocketmine\item\ItemBlock#70895)
Jul 04 09:09 [Server] INFO #7 plugins/VBackpack.phar/src/vennv/vbackpack/data/DataManager(140): vennv\vbackpack\data\DataBackpack->getBackpack()
Jul 04 09:09 [Server] INFO #6 plugins/VBackpack.phar/src/vennv/vbackpack/data/DataBackpack(137): vennv\vbackpack\libs\muqsit\invmenu\InvMenu->send(object pocketmine\player\Player#143677)
Jul 04 09:09 [Server] INFO #5 plugins/VBackpack.phar/src/vennv/vbackpack/libs/muqsit/invmenu/InvMenu(138): vennv\vbackpack\libs\muqsit\invmenu\session\network\PlayerNetwork->waitUntil(int 1, int 0, object Closure#142589)
Jul 04 09:09 [Server] INFO #4 plugins/VBackpack.phar/src/vennv/vbackpack/libs/muqsit/invmenu/session/network/PlayerNetwork(123): vennv\vbackpack\libs\muqsit\invmenu\InvMenu->vennv\vbackpack\libs\muqsit\invmenu\{closure}(true)
Jul 04 09:09 [Server] INFO #3 plugins/VBackpack.phar/src/vennv/vbackpack/libs/muqsit/invmenu/InvMenu(131): vennv\vbackpack\libs\muqsit\invmenu\session\PlayerSession->setCurrentMenu(object vennv\vbackpack\libs\muqsit\invmenu\session\InvMenuInfo#70942, object Closure#70872)
Jul 04 09:09 [Server] INFO #2 plugins/VBackpack.phar/src/vennv/vbackpack/libs/muqsit/invmenu/session/PlayerSession(51): vennv\vbackpack\libs\muqsit\invmenu\type\graphic\MultiBlockInvMenuGraphic->send(object pocketmine\player\Player#143677, null)
Jul 04 09:09 [Server] INFO #1 plugins/VBackpack.phar/src/vennv/vbackpack/libs/muqsit/invmenu/type/graphic/MultiBlockInvMenuGraphic(33): vennv\vbackpack\libs\muqsit\invmenu\type\graphic\BlockActorInvMenuGraphic->send(object pocketmine\player\Player#143677, null)
Jul 04 09:09 [Server] INFO #0 plugins/VBackpack.phar/src/vennv/vbackpack/libs/muqsit/invmenu/type/graphic/BlockActorInvMenuGraphic(48): vennv\vbackpack\libs\muqsit\invmenu\type\graphic\BlockInvMenuGraphic->send(object pocketmine\player\Player#143677, null)
Jul 04 09:09 [Server] INFO --- Stack trace ---
Jul 04 09:09 [Server] CRITICAL Error: "Class "pocketmine\network\mcpe\convert\RuntimeBlockMapping" not found" (EXCEPTION) in "plugins/VBackpack.phar/src/vennv/vbackpack/libs/muqsit/invmenu/type/graphic/BlockInvMenuGraphic" at line 32
Jul 04 09:09 [Server] EMERGENCY Crash occurred while handling a packet from session: EmpireBoss007

take care 
andrew

**Comment by VennDev** [comment]
This may be error from InvMenu API

**Comment by VennDev** [comment]
can you send your plugin let me check ?

**Comment by iTzAndrew33212** [comment]
Oh i see what your saying, i do apologise. which version should i have. I have just noticed that invmenu isnt within the plugins when typing /plugins...

**Comment by VennDev** [comment]
Ok
